# Github actions workflow name
name: CI

# Triggers the workflow on push or pull request events
on:
  push:
    branches: [main]

jobs:
  node_tests:
    name: 'Test @wxml/parser on node${{matrix.node}} width ${{matrix.os}}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14, 16, 18, 20, 22]
    runs-on: ${{ matrix.os }}
    steps:
     # Pull repo to test machine
     - uses: actions/checkout@v2
     # Configures the node version used on GitHub-hosted runners
     - uses: actions/setup-node@v2
       with:
         # The Node.js version to configure
         node-version: ${{ matrix.node }}
     - name: Install npm dependencies
       run: npm install
     - name: Print put node & npm version
       # Output useful info for debugging.
       run: node --version && npm --version 
     - name: Run Test
       run: npm run test
